// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrnGq14XpEQDVAa2-ZXm9xMcuwgWLw6bU',
    appId: '1:494896815514:web:f11542e0682d00fc4fee23',
    messagingSenderId: '494896815514',
    projectId: 'olx-app-63848',
    authDomain: 'olx-app-63848.firebaseapp.com',
    storageBucket: 'olx-app-63848.firebasestorage.app',
    measurementId: 'G-NMCERE4S5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKKuvg6PF3UiMaTGRWjMr3APM_aIzY5Ys',
    appId: '1:494896815514:android:5ed860796b4117984fee23',
    messagingSenderId: '494896815514',
    projectId: 'olx-app-63848',
    storageBucket: 'olx-app-63848.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtfBS9UxfoPzmMnU2y-ZeONe_o8y1GZmU',
    appId: '1:494896815514:ios:2a74892bd61f1aa34fee23',
    messagingSenderId: '494896815514',
    projectId: 'olx-app-63848',
    storageBucket: 'olx-app-63848.firebasestorage.app',
    iosBundleId: 'com.example.olxApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtfBS9UxfoPzmMnU2y-ZeONe_o8y1GZmU',
    appId: '1:494896815514:ios:2a74892bd61f1aa34fee23',
    messagingSenderId: '494896815514',
    projectId: 'olx-app-63848',
    storageBucket: 'olx-app-63848.firebasestorage.app',
    iosBundleId: 'com.example.olxApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrnGq14XpEQDVAa2-ZXm9xMcuwgWLw6bU',
    appId: '1:494896815514:web:1ef23401ce4c8a2f4fee23',
    messagingSenderId: '494896815514',
    projectId: 'olx-app-63848',
    authDomain: 'olx-app-63848.firebaseapp.com',
    storageBucket: 'olx-app-63848.firebasestorage.app',
    measurementId: 'G-VMF95E17PV',
  );
}
